site_name: Test docs
site_description: 'A docs test'
docs_dir: site/content/
site_dir: docs/
repo_name: 'penghaoh/mkdocs-template'
repo_url: 'https://github.com/iamhopaul123/mkdocs-example'
nav:
    - Home: index.md
theme:
  name: 'material'
